name: CalPolyMap
channels:
  - defaults
dependencies:
  - python=3.8
  - cmake=3.22.1
  - notebook=6.5.4
  - plotly=5.19.0
  - dash=2.14.2
  - pip=23.3.1
  - pip:
    - osmium==3.7.0
    - typing_extensions==4.7.1
    - zipp==3.15.0
    - keyboard==0.13.5
    - dash_daq==0.5.0
    - dash_bootstrap_components==1.6.0